# Generated by Django 4.0.2 on 2022-02-06 16:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('cat', 'Kedi'), ('dog', 'Köpek'), ('exotic', 'Egzotik'), ('winged', 'Kanatlı'), ('tropical', 'Tropikal'), ('wild', 'Yabani'), ('other', 'Diğer')], default='other', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Dişi')], default='female', max_length=20)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.customer')),
            ],
        ),
    ]
